openapi: 3.0.0
info:
  title: API PilAPEBack
  version: 1.0.0
  description: API para autenticación de egresados y consulta de empleos.
servers:
  - url: http://localhost:5000
paths:
  /login:
    post:
      summary: Login de egresado
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                cedula:
                  type: string
                  example: "123"
                ficha:
                  type: string
                  example: "456"
      responses:
        '200':
          description: Login exitoso
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                  perfil:
                    type: string
                  nombre:
                    type: string
        '401':
          description: Credenciales inválidas
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
  /trabajos:
    get:
      summary: Obtener trabajos según perfil
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Lista de trabajos
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    titulo:
                      type: string
                    descripcion:
                      type: string
                    salario:
                      type: number
                    perfil_requerido:
                      type: string
        '401':
          description: Token inválido o expirado
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT